# TNT V3: language-pretrained encoder → M1 → Gold

This is the controlled downstream test of the unpaired Wolof encoder. It changes only encoder initialization. Architecture, the 3,330-row M1 sample, optimization, 20 synthetic epochs, 20 Gold epochs, and Gold-dev checkpoint selection match the completed V3 M1 control. Gold-test remains disabled.

In [1]:
from pathlib import Path
import json
import sys
import pandas as pd
import torch

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'src').is_dir():
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.modeling.tnt_hybrid_v3_language_pretraining_gate import (
    completed_language_encoder,
    control_runtime_reference,
    development_comparison,
    gate_protocol,
    load_transfer_data,
    prepare_transferred_initialization,
    run_language_gold_stage,
    run_language_synthetic_stage,
)

print('CUDA:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

c:\Users\thioy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\cuda\__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

CUDA: True
GPU: NVIDIA GeForce RTX 5060 Laptop GPU

## 1. Reload the unchanged V3 protocol and data

The data-preparation function deterministically recreates the same matched M1 sample and locked Gold train/dev split as the random-encoder control.

In [2]:
protocol = gate_protocol()
gold, selected, dataset_audit = load_transfer_data(protocol)

print(protocol)
print('Gold:', {name: len(frame) for name, frame in gold.items()})
print('Selected M1 rows:', len(selected['m1']))
display(dataset_audit)

CompactBenchmarkProtocol(seed=2026, matched_unique_rows=3330, synthetic_epochs=20.0, gold_epochs=20.0, synthetic_learning_rate=0.0003, gold_learning_rate=0.0001, synthetic_batch_size=64, gold_batch_size=32, evaluation_batch_size=64, generated_eval_interval_epochs=5)
Gold: {'train': 142, 'dev': 30, 'test': 29}
Selected M1 rows: 3330

,method,loaded_rows,unique_pair_rows,unique_target_rows,selected_rows,common_target_pool,seed,dev_input_overlap,dev_pair_overlap,test_input_overlap,test_pair_overlap,source_over_255_chars,target_over_255_chars
0,m1,17777,16377,16375,3330,3430,2026,0,0,0,0,8,6
1,m2,17777,16544,16375,3330,3430,2026,0,0,0,0,10,6
2,m3,17777,16384,16375,3330,3430,2026,0,0,0,0,8,6
3,m4,3433,3433,3430,3330,3430,2026,0,0,0,0,7,6
4,m6,17777,16427,16375,3330,3430,2026,0,0,0,0,6,6

## 2. Verify the completed language encoder

Transfer is permitted only when encoder pretraining is complete and its separate unpaired test has been evaluated.

In [3]:
encoder_checkpoint, encoder_vocabulary, encoder_manifest = completed_language_encoder()
print('Encoder:', encoder_checkpoint)
print('Pretraining test evaluated:', encoder_manifest['test_evaluated'])
print('Pretraining test metrics:', json.dumps(encoder_manifest['test_metrics'], indent=2))

Encoder: C:\Users\thioy\Desktop\School\PFE\checkpoints\wolof_encoder_pretraining_v1\476eeb46caee\best_encoder.pt
Pretraining test evaluated: True
Pretraining test metrics: {
  "loss": 2.6500535460557635,
  "masked_accuracy": 0.2698189712972127,
  "masked_characters": 31321,
  "rows": 3018
}

## 3. Create or reuse the transferred initialization

All 120 downstream vocabulary rows must be found in the 272-character pretraining vocabulary. Normalization-operation, replacement, boundary, word, and segment-length heads retain the same seeded random weights as the earlier control.

In [4]:
initialization = prepare_transferred_initialization(gold, selected, protocol)
transfer_manifest = json.loads(
    (initialization / 'initialization_manifest.json').read_text(encoding='utf-8')
)
print('Initialization:', initialization)
print(json.dumps(transfer_manifest['transfer_audit'], indent=2))

[TNT-V3] Reusing initialization: C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\shared_random_base\tnt_hybrid_v3_char_dadd682dc9cc
[language transfer] Reusing C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\language_pretrained_initialization\1e2a3912778b
Initialization: C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\language_pretrained_initialization\1e2a3912778b
{
  "encoder_tensors_copied": 36,
  "position_tensors_copied": 1,
  "target_vocabulary_size": 120,
  "source_vocabulary_size": 272,
  "embedding_rows_copied": 120,
  "embedding_rows_missing": 0,
  "missing_target_tokens": [],
  "exact_encoder_and_position_parameters": 1383744,
  "mapped_embedding_parameters": 23040,
  "total_transferred_parameters": 1406784
}

## 4. Runtime reference

Unlike the small masked-character pretrainer, this uses the existing Hugging Face TNT normalization pipeline. On the previous V3 run, synthetic M1 took about 110 minutes and Gold fine-tuning about 12 minutes. The cells are separated and resumable.

In [5]:
print(json.dumps(control_runtime_reference(), indent=2))

{
  "synthetic_pretrain": 110.42079833333334,
  "gold_finetune_continuous": 11.963973333333334,
  "total": 122.38477166666667
}

## 5. M1 synthetic pretraining

This is the long stage. Training and generated Gold-dev evaluations remain visible. If interrupted, rerun the cell with `rerun=False`; the existing attempt resumes or is reused when complete.

In [6]:
RUN_M1_SYNTHETIC = True
if RUN_M1_SYNTHETIC:
    synthetic_record = run_language_synthetic_stage(
        gold, selected, initialization, protocol, rerun=False
    )
    print('Synthetic checkpoint:', synthetic_record['best_model_path'])
    print('Synthetic dev metrics:', json.dumps(synthetic_record['development_metrics'], indent=2))

[M7] START m1 / synthetic_pretrain / seed 2026 / attempt 001 (trained)
[M7] Output: C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001
[M7] Loading C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\language_pretrained_initialization\1e2a3912778b

You are using a model of type `wolof_tnt_hybrid_v3_transformer` to instantiate a model of type ``. This may be expected if you are loading a checkpoint that shares a subset of the architecture (e.g., loading a `sam2_video` checkpoint into `Sam2Model`), but is otherwise not supported and can yield errors. Please verify that the checkpoint is compatible with the model you are instantiating.

Loading weights:   0%|          | 0/51 [00:00<?, ?it/s]

[M7] Loaded 1,783,707 total parameters; training 1,783,707 (100.0000%) via full_finetune
[M7] Tokenizing 3,330 training and 30 development pairs

Tokenizing TNT edit pairs:   0%|          | 0/3330 [00:00<?, ? examples/s]

Tokenizing TNT edit pairs:   0%|          | 0/30 [00:00<?, ? examples/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

[M7] TNT evaluation route: parallel edit reconstruction; implementation=C:\Users\thioy\Desktop\School\PFE\src\modeling\tnt_hybrid_v3_transformer.py; sha256=0c2dbc688554
[M7] Training starts: 3,330 rows, 20 epochs, physical batch 64, accumulation 1
[M7] Checkpoints are selected by generated development CER every 5 epoch(s)

The following columns in the Training set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.
***** Running training *****
  Num examples = 3,330
  Num Epochs = 20
  Num update steps per epoch = 53
  Instantaneous batch size per device = 64
  Total train batch size (w. parallel, distributed & accumulation) = 64
  Gradient Accumulation steps = 1
  Total optimization steps = 1,060
  Number of trainable parameters = 1,783,707

The following columns in the Evaluation set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
c:\Users\thioy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\transformer.py:515: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. We recommend specifying layout=torch.jagged when constructing a nested tensor, as this layout receives active development, has better operator coverage, and works with torch.compile. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\NestedTensorImpl.cpp:182.)
  output = torch._nested_tensor_from_mask(
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-265
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-265\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-265\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-265\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-265\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-530
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-530\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-530\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-530\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-530\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-795
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-795\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-795\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-795\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-795\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-1060
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-1060\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-1060\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-1060\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-1060\tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-795 (score: 0.19150521609538004).
Deleting older checkpoint [C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\checkpoint-1060] due to args.save_total_limit
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model\tokenizer_config.json
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model\tokenizer_config.json

[M7] Running development prediction and final metrics

The following columns in the test set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Prediction *****
  Num examples = 30
  Batch size = 64

[M7] COMPLETE m1 / synthetic_pretrain / seed 2026 / attempt 001; dev CER=0.19150521609538004
Synthetic checkpoint: C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model
Synthetic dev metrics: {
  "rows": 30,
  "cer": 0.19150521609538004,
  "wer": 0.5966101694915255,
  "chrf": 59.64092075657178,
  "exact_match": 0.0,
  "correction_tp": 3,
  "correction_fp": 72,
  "correction_fn": 69,
  "correction_precision": 0.04,
  "correction_recall": 0.041666666666666664,
  "correction_f1": 0.04081632653061224,
  "overcorrection_rate": 0.96,
  "unchanged_reference_rows": 0,
  "unchanged_sentence_overcorrection_rate": 0.0
}

## 6. Gold-train fine-tuning

Run only after the synthetic stage reports complete. Restarting the notebook is safe: the cell reloads the completed synthetic stage before beginning or resuming Gold fine-tuning.

In [7]:
RUN_GOLD_FINETUNE = True
if RUN_GOLD_FINETUNE:
    if 'synthetic_record' not in globals():
        synthetic_record = run_language_synthetic_stage(
            gold, selected, initialization, protocol, rerun=False
        )
    gold_selection = run_language_gold_stage(
        gold, synthetic_record, protocol, rerun=False
    )
    print(json.dumps(gold_selection['development_metrics'], indent=2))

[M7] START m1 / gold_finetune_continuous / seed 2026 / attempt 001 (trained)
[M7] Output: C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001
[M7] Loading C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model

loading configuration file C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model\config.json
loading configuration file C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model\config.json
You are using a model of type `wolof_tnt_hybrid_v3_transformer` to instantiate a model of type ``. This may be expected if you are loading a checkpoint that shares a subset of the architecture (e.g., loading a `sam2_video` checkpoint into `Sam2Model`), but is otherwise not supported and can yield errors. Please verify that the checkpoint is compatible with the model you are instantiating.
Model config PreTrainedConfig {
  "architectures": [
    "TntHybridV3TransformerForConditionalGeneration"
  ],
  "attention_heads": 4,
  "bos_token_id": 1,
  "boundary_class_weights": [
    0.5533591001386836,
    1.2271996237756158,
    4.0,
    4.0
  ],
  "boundary_confidence_threshold": 0.5,
  "boundary_focal_gamma": 2.0,
  "boundary_loss_weight": 1.0,
  "character_loss_weight": 1.0,
  "d_model": 192,
  "decoder_start_token_id": 1,
  "dropout": 0.1,
  "dtype": "float32",
  "encoder_layers": 3,
  "eos_token_id": 2,
  "feed_forward_size": 768,
  "hidden_size": 192,
  "is_encoder_decoder": true,
  "label_smoothing": 0.1,
  "lowercase_token_id_map": {
    "10": 10,
    "100": 100,
    "101": 101,
    "102": 102,
    "103": 103,
    "104": 104,
    "105": 105,
    "106": 106,
    "107": 107,
    "108": 108,
    "109": 109,
    "11": 11,
    "110": 110,
    "111": 111,
    "112": 112,
    "113": 113,
    "114": 114,
    "115": 115,
    "116": 116,
    "117": 117,
    "118": 118,
    "119": 119,
    "12": 12,
    "13": 13,
    "14": 14,
    "15": 15,
    "16": 16,
    "17": 17,
    "18": 18,
    "19": 19,
    "20": 20,
    "21": 21,
    "22": 22,
    "23": 23,
    "24": 24,
    "25": 25,
    "26": 26,
    "27": 27,
    "28": 28,
    "29": 29,
    "30": 30,
    "31": 61,
    "32": 62,
    "33": 63,
    "34": 64,
    "35": 65,
    "36": 66,
    "37": 67,
    "38": 68,
    "39": 69,
    "4": 4,
    "40": 70,
    "41": 71,
    "42": 72,
    "43": 73,
    "44": 74,
    "45": 75,
    "46": 76,
    "47": 77,
    "48": 78,
    "49": 79,
    "5": 5,
    "50": 80,
    "51": 81,
    "52": 82,
    "53": 83,
    "54": 84,
    "55": 85,
    "56": 86,
    "57": 57,
    "58": 58,
    "59": 59,
    "6": 6,
    "60": 60,
    "61": 61,
    "62": 62,
    "63": 63,
    "64": 64,
    "65": 65,
    "66": 66,
    "67": 67,
    "68": 68,
    "69": 69,
    "7": 7,
    "70": 70,
    "71": 71,
    "72": 72,
    "73": 73,
    "74": 74,
    "75": 75,
    "76": 76,
    "77": 77,
    "78": 78,
    "79": 79,
    "8": 8,
    "80": 80,
    "81": 81,
    "82": 82,
    "83": 83,
    "84": 84,
    "85": 85,
    "86": 86,
    "87": 87,
    "88": 88,
    "89": 92,
    "9": 9,
    "90": 98,
    "91": 101,
    "92": 92,
    "93": 93,
    "94": 94,
    "95": 95,
    "96": 96,
    "97": 97,
    "98": 98,
    "99": 99
  },
  "max_position_embeddings": 256,
  "num_boundary_actions": 4,
  "num_operations": 4,
  "num_segment_lengths": 17,
  "num_word_actions": 2,
  "num_word_features": 3,
  "operation_class_weights": [
    0.5553579980883788,
    1.9817851870151133,
    1.6380424851581792,
    2.76939125025622
  ],
  "operation_loss_weight": 1.0,
  "output_slots_per_source": 16,
  "pad_token_id": 0,
  "segment_length_class_weights": [
    4.0,
    0.28178525927398834,
    0.4947986540614295,
    2.0992529016528807,
    4.0,
    4.0,
    4.0,
    4.0,
    4.0,
    4.0,
    4.0,
    4.0,
    4.0,
    4.0,
    4.0,
    4.0,
    4.0
  ],
  "segment_length_loss_weight": 1.0,
  "space_token_id": 4,
  "transformers_version": "5.5.4",
  "use_boundary_inference": true,
  "use_hard_lexical_protection": true,
  "use_lexical_word_features": true,
  "use_word_keep_gate": true,
  "vocab_size": 120,
  "word_class_weights": [
    0.9769410897842448,
    1.0247727727007534
  ],
  "word_edge_strip_token_ids": [
    4,
    5,
    6,
    7,
    8,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    27,
    28,
    29,
    30,
    57,
    58,
    59,
    60,
    87,
    88,
    114,
    115,
    116,
    117,
    118,
    119
  ],
  "word_feature_lookup": {
    "101,61,61,78": [
      0,
      0,
      0
    ],
    "101,61,61,78,65,65,72": [
      0,
      0,
      0
    ],
    "101,61,61,80,61": [
      0,
      0,
      0
    ],
    "101,61,61,83": [
      0,
      0,
      0
    ],
    "101,69": [
      0,
      0,
      0
    ],
    "101,75,75": [
      0,
      0,
      0
    ],
    "101,81": [
      0,
      0,
      0
    ],
    "101,81,81,79": [
      0,
      0,
      0
    ],
    "101,81,81,79,81,72": [
      0,
      0,
      0
    ],
    "101,92,71,71": [
      0,
      0,
      0
    ],
    "101,98,83": [
      0,
      0,
      0
    ],
    "60,60,76,78,75,80,65,63,80,65,64,60,17,60,60": [
      0,
      0,
      0
    ],
    "61,100,63,68,61": [
      0,
      1,
      1
    ],
    "61,100,64,61": [
      0,
      1,
      1
    ],
    "61,100,64,61,78,61": [
      0,
      1,
      1
    ],
    "61,100,74,69,74,61": [
      0,
      1,
      1
    ],
    "61,100,79,79,61,80,75,81": [
      0,
      1,
      1
    ],
    "61,61,83,75": [
      0,
      0,
      0
    ],
    "61,62,62,61": [
      0,
      1,
      1
    ],
    "61,62,64,61,72,72,61,68": [
      0,
      1,
      1
    ],
    "61,62,64,75,81": [
      0,
      1,
      1
    ],
    "61,62,64,75,81,72,61,80,69,66": [
      0,
      1,
      1
    ],
    "61,62,64,75,81,72,61,85,65": [
      0,
      1,
      1
    ],
    "61,62,64,75,81,78,61,68,73,61,74,65": [
      0,
      1,
      1
    ],
    "61,62,69,62,61,80,75,81": [
      0,
      1,
      1
    ],
    "61,62,72,61,85,65": [
      0,
      1,
      1
    ],
    "61,62,75,81": [
      0,
      1,
      1
    ],
    "61,62,79,61": [
      0,
      1,
      1
    ],
    "61,62,85": [
      0,
      1,
      1
    ],
    "61,64,61,73,61": [
      0,
      1,
      1
    ],
    "61,64,69,75,81,73,61": [
      0,
      1,
      1
    ],
    "61,64,70,61": [
      0,
      1,
      1
    ],
    "61,64,70,61,74,61": [
      0,
      0,
      0
    ],
    "61,64,70,69": [
      0,
      1,
      1
    ],
    "61,64,75": [
      1,
      0,
      1
    ],
    "61,67,75,81,72,75,81,62,65,74,65": [
      0,
      1,
      1
    ],
    "61,68": [
      1,
      0,
      1
    ],
    "61,68,68,68": [
      0,
      0,
      0
    ],
    "61,68,68,68,68,68": [
      1,
      0,
      0
    ],
    "61,69,63,68,61": [
      0,
      1,
      1
    ],
    "61,69,64,61": [
      1,
      0,
      1
    ],
    "61,71": [
      0,
      0,
      0
    ],
    "61,71,61": [
      0,
      0,
      0
    ],
    "61,71,68": [
      0,
      0,
      0
    ],
    "61,71,69,74,81,73,65,72,75,62": [
      0,
      1,
      1
    ],
    "61,72": [
      0,
      0,
      0
    ],
    "61,72,61,64,70,69": [
      0,
      1,
      1
    ],
    "61,72,61,79,79,61,74,65": [
      0,
      1,
      1
    ],
    "61,72,62,75,81,78,69": [
      0,
      1,
      1
    ],
    "61,72,66,61": [
      0,
      1,
      1
    ],
    "61,72,66,75,81,79,79,65,85,74,69": [
      0,
      1,
      1
    ],
    "61,72,68,61,73,64,75,81,72,69,72,61,68": [
      0,
      0,
      1
    ],
    "61,72,69,73,61": [
      0,
      1,
      1
    ],
    "61,72,69,73,61,80,75,81": [
      0,
      1,
      1
    ],
    "61,72,69,74,79,69,69,80,75,83,65": [
      0,
      1,
      1
    ],
    "61,72,69,75,81": [
      0,
      1,
      1
    ],
    "61,72,69,75,81,74,65": [
      0,
      1,
      1
    ],
    "61,72,70,61,74,74,61": [
      0,
      0,
      0
    ],
    "61,72,72,96": [
      0,
      1,
      1
    ],
    "61,72,73,61,73,85": [
      0,
      1,
      1
    ],
    "61,72,75,65,74,64,69,79,79,75": [
      0,
      1,
      1
    ],
    "61,72,80,69,74,65": [
      0,
      1,
      1
    ],
    "61,73": [
      0,
      0,
      0
    ],
    "61,73,61": [
      0,
      1,
      1
    ],
    "61,73,61,64,75,81": [
      0,
      1,
      1
    ],
    "61,73,61,72": [
      0,
      0,
      0
    ],
    "61,73,61,72,65": [
      0,
      0,
      0
    ],
    "61,73,61,78,61": [
      0,
      1,
      1
    ],
    "61,73,61,80,68": [
      0,
      1,
      1
    ],
    "61,73,64,85": [
      0,
      1,
      1
    ],
    "61,73,65": [
      0,
      0,
      0
    ],
    "61,73,69,64,75,81": [
      0,
      1,
      1
    ],
    "61,73,69,74,61,80,61": [
      0,
      1,
      1
    ],
    "61,73,69,74,63,80,61": [
      0,
      1,
      1
    ],
    "61,73,73": [
      0,
      0,
      0
    ],
    "61,73,73,65,69": [
      0,
      0,
      0
    ],
    "61,73,74,61": [
      0,
      0,
      0
    ],
    "61,73,75,74,65": [
      0,
      0,
      0
    ],
    "61,73,75,75,74": [
      0,
      0,
      0
    ],
    "61,73,75,81,72": [
      0,
      0,
      0
    ],
    "61,73,75,81,74,80": [
      0,
      0,
      0
    ],
    "61,73,81,72": [
      0,
      0,
      0
    ],
    "61,73,85": [
      0,
      1,
      1
    ],
    "61,74,64": [
      0,
      0,
      0
    ],
    "61,74,79": [
      1,
      0,
      1
    ],
    "61,74,79,75,81,73,61,74,65": [
      0,
      1,
      1
    ],
    "61,74,80,61": [
      0,
      1,
      1
    ],
    "61,76,76,61,78,65,73,73,65,74,80": [
      1,
      0,
      1
    ],
    "61,76,76,61,78,80,65,73,65,74,80": [
      1,
      0,
      1
    ],
    "61,78,61,73,65": [
      0,
      1,
      1
    ],
    "61,78,66,61,74,67": [
      0,
      1,
      1
    ],
    "61,78,75,74,61": [
      0,
      1,
      1
    ],
    "61,79,79,61": [
      0,
      1,
      1
    ],
    "61,79,79,61,74,65": [
      0,
      1,
      1
    ],
    "61,79,79,65": [
      0,
      1,
      1
    ],
    "61,79,79,69,65,80,75,81": [
      0,
      1,
      1
    ],
    "61,79,79,81,78,65": [
      1,
      0,
      1
    ],
    "61,79,80,75,81": [
      0,
      1,
      1
    ],
    "61,80,61": [
      0,
      1,
      1
    ],
    "61,80,69,61": [
      0,
      1,
      1
    ],
    "61,81,79,79,69": [
      1,
      0,
      1
    ],
    "61,81,80,75,73": [
      0,
      0,
      0
    ],
    "61,82,61,74,80": [
      1,
      0,
      1
    ],
    "61,82,69,79": [
      1,
      0,
      1
    ],
    "61,83,61": [
      0,
      1,
      1
    ],
    "61,83,65,74,80,75,78,96,62,96": [
      0,
      1,
      1
    ],
    "61,83,75": [
      0,
      0,
      0
    ],
    "61,85": [
      0,
      0,
      0
    ],
    "61,85,69,73,76,65,74": [
      0,
      1,
      1
    ],
    "61,86,69,86": [
      0,
      1,
      1
    ],
    "62,61": [
      0,
      0,
      0
    ],
    "62,61,100,64,69": [
      0,
      1,
      1
    ],
    "62,61,101": [
      0,
      0,
      0
    ],
    "62,61,101,61": [
      0,
      0,
      0
    ],
    "62,61,61,62,61": [
      0,
      1,
      1
    ],
    "62,61,61,72,75,81": [
      0,
      0,
      0
    ],
    "62,61,61,72,81": [
      0,
      0,
      0
    ],
    "62,61,61,84": [
      0,
      0,
      0
    ],
    "62,61,62,61,63,61,78": [
      0,
      1,
      1
    ],
    "62,61,62,65,72": [
      1,
      0,
      1
    ],
    "62,61,62,75,81": [
      0,
      1,
      1
    ],
    "62,61,62,85": [
      1,
      0,
      1
    ],
    "62,61,63,61,78": [
      0,
      1,
      1
    ],
    "62,61,64,61,78,61": [
      0,
      1,
      1
    ],
    "62,61,64,69,65,74,65": [
      0,
      0,
      0
    ],
    "62,61,64,75,81": [
      0,
      1,
      1
    ],
    "62,61,67,74,65": [
      0,
      0,
      0
    ],
    "62,61,69,72,61": [
      0,
      1,
      1
    ],
    "62,61,71,61,78,69": [
      0,
      1,
      1
    ],
    "62,61,71,68": [
      0,
      0,
      0
    ],
    "62,61,71,68,61": [
      0,
      0,
      0
    ],
    "62,61,71,69,78": [
      0,
      1,
      1
    ],
    "62,61,72,61": [
      0,
      0,
      0
    ],
    "62,61,72,61,61": [
      0,
      0,
      0
    ],
    "62,61,72,72,61,67,75": [
      0,
      1,
      1
    ],
    "62,61,73,62,61": [
      0,
      1,
      1
    ],
    "62,61,73,75,85": [
      0,
      0,
      0
    ],
    "62,61,73,96,72,75,81": [
      0,
      0,
      0
    ],
    "62,61,74": [
      0,
      0,
      0
    ],
    "62,61,74,65": [
      0,
      0,
      0
    ],
    "62,61,74,65,72": [
      0,
      1,
      1
    ],
    "62,61,74,67,61,85": [
      0,
      0,
      0
    ],
    "62,61,74,69,61": [
      0,
      0,
      0
    ],
    "62,61,74,80,61": [
      0,
      1,
      1
    ],
    "62,61,78,61": [
      0,
      1,
      1
    ],
    "62,61,78,69": [
      0,
      0,
      0
    ],
    "62,61,78,69,74,61": [
      0,
      0,
      0
    ],
    "62,61,79,79,69,78,75,81": [
      0,
      1,
      1
    ],
    "62,61,80,68,69,65": [
      0,
      1,
      1
    ],
    "62,61,80,75,81,72,85": [
      0,
      1,
      1
    ],
    "62,61,85,69": [
      0,
      0,
      0
    ],
    "62,61,85,69,71,75,66,69": [
      0,
      0,
      0
    ],
    "62,61,85,69,72": [
      0,
      0,
      0
    ],
    "62,61,85,69,72,61": [
      0,
      0,
      0
    ],
    "62,61,85,75": [
      0,
      1,
      1
    ],
    "62,62": [
      1,
      0,
      0
    ],
    "62,65,63,61,85,65": [
      0,
      1,
      1
    ],
    "62,65,74": [
      0,
      0,
      0
    ],
    "62,65,74,65": [
      1,
      0,
      1
    ],
    "62,65,74,74": [
      0,
      0,
      0
    ],
    "62,65,80,80": [
      0,
      0,
      0
    ],
    "62,65,81,67": [
      0,
      0,
      0
    ],
    "62,65,81,67,81,61,80,65": [
      0,
      0,
      0
    ],
    "62,65,81,67,81,65": [
      0,
      0,
      0
    ],
    "62,65,81,67,81,65,81": [
      0,
      0,
      0
    ],
    "62,69": [
      0,
      0,
      0
    ],
    "62,69,67,81,96": [
      0,
      1,
      1
    ],
    "62,69,69": [
      0,
      0,
      0
    ],
    "62,69,72,61,68,69": [
      0,
      0,
      1
    ],
    "62,69,72,61,72": [
      0,
      1,
      1
    ],
    "62,69,72,61,85": [
      0,
      0,
      0
    ],
    "62,69,72,72,96": [
      0,
      1,
      1
    ],
    "62,69,74,63,80,61": [
      0,
      1,
      1
    ],
    "62,69,74,65,80,61": [
      0,
      1,
      1
    ],
    "62,69,74,65,80,80,65": [
      0,
      1,
      1
    ],
    "62,69,74,80,61": [
      0,
      1,
      1
    ],
    "62,69,74,80,75,81": [
      0,
      1,
      1
    ],
    "62,69,78,61,73": [
      0,
      1,
      1
    ],
    "62,69,78,61,73,65": [
      0,
      1,
      1
    ],
    "62,69,78,61,74,65": [
      0,
      1,
      1
    ],
    "62,69,78,69,73,61": [
      0,
      1,
      1
    ],
    "62,69,78,85": [
      0,
      1,
      1
    ],
    "62,69,79": [
      0,
      0,
      0
    ],
    "62,75": [
      0,
      0,
      0
    ],
    "62,75,63,61,78": [
      0,
      1,
      1
    ],
    "62,75,64,69,65,72": [
      0,
      1,
      1
    ],
    "62,75,69,78,69,71,61": [
      0,
      1,
      1
    ],
    "62,75,72,69,71,75,78,75": [
      0,
      1,
      1
    ],
    "62,75,74": [
      0,
      0,
      0
    ],
    "62,75,74,65,67,61": [
      0,
      0,
      0
    ],
    "62,75,74,74,65": [
      0,
      0,
      0
    ],
    "62,75,74,75,81,72": [
      0,
      0,
      0
    ],
    "62,75,74,81,72": [
      0,
      0,
      0
    ],
    "62,75,75": [
      0,
      0,
      0
    ],
    "62,75,75,76": [
      0,
      0,
      0
    ],
    "62,75,76,61,73": [
      0,
      0,
      0
    ],
    "62,75,76,76": [
      0,
      0,
      0
    ],
    "62,75,76,76,61,73": [
      0,
      0,
      0
    ],
    "62,75,78,75,73": [
      0,
      0,
      0
    ],
    "62,75,81": [
      0,
      0,
      0
    ],
    "62,75,81,62,61,63,61,78": [
      0,
      1,
      1
    ],
    "62,75,81,62,75,81": [
      0,
      1,
      1
    ],
    "62,75,81,67,75,81,73,61": [
      0,
      1,
      1
    ],
    "62,75,81,71,75": [
      0,
      0,
      0
    ],
    "62,75,81,72,65": [
      0,
      0,
      0
    ],
    "62,75,81,72,85": [
      0,
      1,
      1
    ],
    "62,75,81,73,61,72,61": [
      0,
      0,
      0
    ],
    "62,75,81,73,75,81": [
      0,
      0,
      0
    ],
    "62,75,81,74,61": [
      0,
      1,
      1
    ],
    "62,75,81,78,71,68,61,74,65": [
      0,
      1,
      1
    ],
    "62,75,81,78,85": [
      0,
      1,
      1
    ],
    "62,75,81,79,79,75": [
      0,
      1,
      1
    ],
    "62,75,81,80,69,80,75,81": [
      0,
      0,
      0
    ],
    "62,75,85": [
      0,
      0,
      1
    ],
    "62,78,61,74,79,61,74": [
      0,
      1,
      1
    ],
    "62,78,61,82,75": [
      1,
      0,
      1
    ],
    "62,81": [
      0,
      0,
      0
    ],
    "62,81,72": [
      0,
      0,
      0
    ],
    "62,81,74,65,68": [
      0,
      0,
      0
    ],
    "62,81,80,69,80,81": [
      0,
      0,
      0
    ],
    "62,92,70,70,65,74": [
      0,
      0,
      0
    ],
    "62,92,73,73,65,65,72,81": [
      0,
      0,
      0
    ],
    "62,92,85,85,69": [
      0,
      0,
      0
    ],
    "62,92,85,85,69,72": [
      0,
      0,
      0
    ],
    "62,96,62,96": [
      1,
      0,
      1
    ],
    "62,96,67,65,81,80,75,81": [
      0,
      0,
      0
    ],
    "62,96,74,65": [
      0,
      0,
      0
    ],
    "62,96,74,74,65": [
      0,
      0,
      0
    ],
    "62,96,79": [
      0,
      0,
      0
    ],
    "62,96,80,65,81": [
      0,
      0,
      0
    ],
    "62,98,67,67": [
      0,
      0,
      0
    ],
    "62,98,67,67,61,74,80,65": [
      0,
      0,
      0
    ],
    "62,98,67,67,98,80,81": [
      0,
      0,
      0
    ],
    "63,61,66,96": [
      1,
      0,
      1
    ],
    "63,61,76,76": [
      0,
      0,
      0
    ],
    "63,61,79,80,69,74,67": [
      1,
      0,
      1
    ],
    "63,68,65,69,71,68": [
      1,
      1,
      1
    ],
    "63,68,65,78,63,68,65": [
      1,
      0,
      1
    ],
    "63,68,69,65,71,68": [
      0,
      1,
      1
    ],
    "63,68,96,78,69,66": [
      0,
      1,
      1
    ],
    "63,69": [
      0,
      0,
      0
    ],
    "63,69,73": [
      0,
      0,
      0
    ],
    "63,69,78,61,73,61,64,69": [
      0,
      1,
      1
    ],
    "63,69,78,96": [
      0,
      1,
      1
    ],
    "63,75,64,75,81": [
      0,
      1,
      1
    ],
    "63,75,73,62,96": [
      0,
      1,
      1
    ],
    "63,75,73,73,65": [
      1,
      0,
      1
    ],
    "63,75,73,73,65,74,63,65,78": [
      1,
      0,
      1
    ],
    "63,75,73,73,65,74,80": [
      1,
      0,
      1
    ],
    "63,75,74,63,65,74,80,78,96": [
      1,
      0,
      1
    ],
    "63,75,74,80,61,74,61": [
      0,
      0,
      0
    ],
    "63,75,74,80,69,74,81,65,78": [
      1,
      0,
      1
    ],
    "63,75,81": [
      0,
      0,
      0
    ],
    "63,75,81,64,75,81,81,80,69,75,74": [
      0,
      1,
      1
    ],
    "63,75,81,73,62,61": [
      0,
      1,
      1
    ],
    "63,75,81,73,62,75,85,65": [
      0,
      1,
      1
    ],
    "63,75,81,76,72,65": [
      1,
      0,
      1
    ],
    "63,75,81,78,61": [
      0,
      1,
      1
    ],
    "63,9,65,79,80": [
      1,
      0,
      1
    ],
    "63,96,85": [
      0,
      0,
      0
    ],
    "64": [
      0,
      0,
      0
    ],
    "64,104,73,65": [
      0,
      0,
      0
    ],
    "64,61": [
      0,
      0,
      0
    ],
    "64,61,101": [
      0,
      0,
      0
    ],
    "64,61,101,81": [
      0,
      0,
      0
    ],
    "64,61,61,72": [
      0,
      0,
      0
    ],
    "64,61,62,61": [
      0,
      1,
      1
    ],
    "64,61,64,75": [
      0,
      1,
      1
    ],
    "64,61,66,61": [
      0,
      0,
      0
    ],
    "64,61,66,61,85": [

Loading weights:   0%|          | 0/51 [00:00<?, ?it/s]

loading configuration file C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\synthetic_pretrain\attempt_001\best_model\generation_config.json
Generate config GenerationConfig {
  "assistant_confidence_threshold": 0.4,
  "assistant_lookbehind": 10,
  "bos_token_id": 1,
  "decoder_start_token_id": 1,
  "diversity_penalty": 0.0,
  "do_sample": false,
  "early_stopping": false,
  "encoder_no_repeat_ngram_size": 0,
  "encoder_repetition_penalty": 1.0,
  "eos_token_id": [
    2
  ],
  "epsilon_cutoff": 0.0,
  "eta_cutoff": 0.0,
  "length_penalty": 1.0,
  "max_length": 20,
  "min_length": 0,
  "no_repeat_ngram_size": 0,
  "num_assistant_tokens": 20,
  "num_assistant_tokens_schedule": "constant",
  "num_beam_groups": 1,
  "num_beams": 1,
  "num_return_sequences": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_scores": false,
  "pad_token_id": 0,
  "remove_invalid_values": false,
  "repetition_penalty": 1.0,
  "return_dict_in_generate": false,
  "target_lookbehind": 10,
  "temperature": 1.0,
  "top_k": 50,
  "top_p": 1.0,
  "typical_p": 1.0,
  "use_cache": true
}

[M7] Loaded 1,783,707 total parameters; training 1,783,707 (100.0000%) via full_finetune
[M7] Tokenizing 142 training and 30 development pairs

Tokenizing TNT edit pairs:   0%|          | 0/142 [00:00<?, ? examples/s]

Tokenizing TNT edit pairs:   0%|          | 0/30 [00:00<?, ? examples/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
PyTorch: setting up devices

[M7] TNT evaluation route: parallel edit reconstruction; implementation=C:\Users\thioy\Desktop\School\PFE\src\modeling\tnt_hybrid_v3_transformer.py; sha256=0c2dbc688554
[M7] Training starts: 142 rows, 20 epochs, physical batch 32, accumulation 1
[M7] Checkpoints are selected by generated development CER every 5 epoch(s)

The following columns in the Training set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.
***** Running training *****
  Num examples = 142
  Num Epochs = 20
  Num update steps per epoch = 5
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 100
  Number of trainable parameters = 1,783,707

The following columns in the Evaluation set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-75
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-75\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-75\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-75\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-75\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100\tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25 (score: 0.1870342771982116).
Deleting older checkpoint [C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100] due to args.save_total_limit
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model\tokenizer_config.json
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_v3_language_pretrained_m1_gate_v1\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model\tokenizer_config.json

[M7] Running development prediction and final metrics

The following columns in the test set don't have a corresponding argument in `TntHybridV3TransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridV3TransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Prediction *****
  Num examples = 30
  Batch size = 64

[M7] COMPLETE m1 / gold_finetune_continuous / seed 2026 / attempt 001; dev CER=0.1870342771982116
[compact benchmark] m1: continuous 20-epoch gold run complete; selected dev CER=0.1870342771982116
{
  "rows": 30,
  "cer": 0.1870342771982116,
  "wer": 0.6440677966101694,
  "chrf": 63.07658337289543,
  "exact_match": 0.0,
  "correction_tp": 3,
  "correction_fp": 74,
  "correction_fn": 69,
  "correction_precision": 0.03896103896103896,
  "correction_recall": 0.041666666666666664,
  "correction_f1": 0.040268456375838924,
  "overcorrection_rate": 0.961038961038961,
  "unchanged_reference_rows": 0,
  "unchanged_sentence_overcorrection_rate": 0.0
}

## 7. Controlled Gold-dev comparison

The decisive comparison is against the completed random-encoder V3 M1 run. Lower CER/WER and overcorrection, and higher chrF/correction F1, indicate improvement. This cell never opens Gold-test.

In [8]:
comparison = development_comparison(gold['dev'])
display(comparison)

,condition,initialization,rows,cer,wer,chrf,exact_match,correction_tp,correction_fp,correction_fn,correction_precision,correction_recall,correction_f1,overcorrection_rate,unchanged_reference_rows,unchanged_sentence_overcorrection_rate
0,identity,none,30,0.233234,0.630508,56.052143,0.0,0,0,72,0.000000,0.000000,0.000000,0.000000,0,0.0
1,m1_v3_random_encoder,seeded random,30,0.194486,0.691525,59.948595,0.0,2,69,70,0.028169,0.027778,0.027972,0.971831,0,0.0
2,m1_v3_language_pretrained_encoder,unpaired formal+informal MLM,30,0.187034,0.644068,63.076583,0.0,3,74,69,0.038961,0.041667,0.040268,0.961039,0,0.0