# TNT hybrid M1 pretraining gate

This experiment answers one question before any further ablation: **does the full hybrid improve on TNT V1 when both are pretrained on M1 and fine-tuned on Gold-train under the same budget?**

Protocol: 3,330 matched M1 pairs, 20 synthetic epochs, 20 Gold epochs, seed 2026, checkpoint selection on Gold-dev every five epochs. Gold-test is disabled. The V2 operation/boundary/word class weights are calculated once from Gold-train and frozen before M1 training. The bounded segment head uses 16 slots: the observed maximum is 14 across M1 plus Gold-train, while 99% of pairs require at most two.

In [2]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve()
if not (PROJECT_ROOT / 'src').is_dir():
    candidates = [parent for parent in PROJECT_ROOT.parents if (parent / 'src').is_dir()]
    if not candidates:
        raise FileNotFoundError('Run from the PFE repository or one of its subdirectories.')
    PROJECT_ROOT = candidates[0]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd
import torch
from IPython.display import display

from src.modeling.tnt_hybrid_m1_gate import (
    BENCHMARK_NAME,
    RESULTS_DIR,
    gate_decision,
    gate_prediction_comparison,
    gate_protocol,
    gate_summary,
    prepare_gate_data,
    prepare_gate_initialization,
    run_m1_gate,
)
from src.modeling.tnt_hybrid_diagnostics import (
    DIAGNOSTIC_DIR,
    run_head_diagnostics,
)

print('Project:', PROJECT_ROOT)
print('Experiment:', BENCHMARK_NAME)
print('Results:', RESULTS_DIR.resolve())
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

c:\Users\thioy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\cuda\__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

Project: C:\Users\thioy\Desktop\School\PFE
Experiment: tnt_hybrid_m1_gate_v2
Results: C:\Users\thioy\Desktop\School\PFE\results\m7_seq2seq\tnt_hybrid_m1_gate_v2
CUDA available: True
GPU: NVIDIA GeForce RTX 5060 Laptop GPU

## 1. Recreate the controlled data selection

This uses the same common-target sampling policy as the frozen benchmark. All retained methods are loaded only to recreate the shared 3,330 formal-target pool and character vocabulary; **only M1 is trained**.

In [3]:
PROTOCOL = gate_protocol()
gold, selected, dataset_audit = prepare_gate_data(PROTOCOL)
display(pd.DataFrame([PROTOCOL.__dict__]))
display(dataset_audit)
print('M1 selected rows:', len(selected['m1']))
print('Gold train/dev rows:', len(gold['train']), len(gold['dev']))

,seed,matched_unique_rows,synthetic_epochs,gold_epochs,synthetic_learning_rate,gold_learning_rate,synthetic_batch_size,gold_batch_size,evaluation_batch_size,generated_eval_interval_epochs
0,2026,3330,20.0,20.0,0.0003,0.0001,64,32,64,5

,method,loaded_rows,unique_pair_rows,unique_target_rows,selected_rows,common_target_pool,seed,dev_input_overlap,dev_pair_overlap,test_input_overlap,test_pair_overlap,source_over_255_chars,target_over_255_chars
0,m1,17777,16377,16375,3330,3430,2026,0,0,0,0,8,6
1,m2,17777,16544,16375,3330,3430,2026,0,0,0,0,10,6
2,m3,17777,16384,16375,3330,3430,2026,0,0,0,0,8,6
3,m4,3433,3433,3430,3330,3430,2026,0,0,0,0,7,6
4,m6,17777,16427,16375,3330,3430,2026,0,0,0,0,6,6

M1 selected rows: 3330
Gold train/dev rows: 142 30

## 2. Prepare the full-hybrid initialization

This creates the model and tokenizer but does not train them. Re-running the cell reuses the fingerprinted initialization.

In [4]:
shared_initialization = prepare_gate_initialization(gold, selected, PROTOCOL)
print('Initialization:', shared_initialization.resolve())

[TNT-V2] Reusing hybrid initialization: C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\shared_initialization\tnt_hybrid_char_e702b9f11b13
Initialization: C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\shared_initialization\tnt_hybrid_char_e702b9f11b13

## 3. Run M1 synthetic pretraining → Gold fine-tuning

The cell prints tqdm progress, evaluation metrics and both stages. Interrupted checkpoints are resumed when possible. Leave `RERUN=False` to reuse a completed gate; use `True` only when intentionally creating a fresh attempt.

In [5]:
RUN_M1_GATE = True
RERUN = False

if RUN_M1_GATE:
    m1_gate_selection = run_m1_gate(
        gold, selected, shared_initialization, PROTOCOL, rerun=RERUN
    )
    display(m1_gate_selection.get('development_metrics', {}))
else:
    print('Skipped. Set RUN_M1_GATE=True when ready to train.')

[M7] START m1 / synthetic_pretrain / seed 2026 / attempt 002 (trained)
[M7] Output: C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002
[M7] Loading C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\shared_initialization\tnt_hybrid_char_e702b9f11b13

You are using a model of type `wolof_tnt_hybrid_transformer` to instantiate a model of type ``. This may be expected if you are loading a checkpoint that shares a subset of the architecture (e.g., loading a `sam2_video` checkpoint into `Sam2Model`), but is otherwise not supported and can yield errors. Please verify that the checkpoint is compatible with the model you are instantiating.

Loading weights:   0%|          | 0/46 [00:00<?, ?it/s]

[M7] Loaded 1,779,274 total parameters; training 1,779,274 (100.0000%) via full_finetune
[M7] Tokenizing 3,330 training and 30 development pairs

Tokenizing TNT edit pairs:   0%|          | 0/3330 [00:00<?, ? examples/s]

Tokenizing TNT edit pairs:   0%|          | 0/30 [00:00<?, ? examples/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

[M7] TNT evaluation route: parallel edit reconstruction; implementation=C:\Users\thioy\Desktop\School\PFE\src\modeling\tnt_hybrid_transformer.py; sha256=46ba78889f26
[M7] Training starts: 3,330 rows, 20 epochs, physical batch 64, accumulation 1
[M7] Checkpoints are selected by generated development CER every 5 epoch(s)

The following columns in the Training set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.
***** Running training *****
  Num examples = 3,330
  Num Epochs = 20
  Num update steps per epoch = 53
  Instantaneous batch size per device = 64
  Total train batch size (w. parallel, distributed & accumulation) = 64
  Gradient Accumulation steps = 1
  Total optimization steps = 1,060
  Number of trainable parameters = 1,779,274

The following columns in the Evaluation set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
c:\Users\thioy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\transformer.py:515: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. We recommend specifying layout=torch.jagged when constructing a nested tensor, as this layout receives active development, has better operator coverage, and works with torch.compile. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\NestedTensorImpl.cpp:182.)
  output = torch._nested_tensor_from_mask(
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-265
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-265\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-265\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-265\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-265\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-530
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-530\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-530\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-530\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-530\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-795
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-795\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-795\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-795\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-795\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-1060
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-1060\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-1060\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-1060\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-1060\tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-795 (score: 0.23472429210134127).
Deleting older checkpoint [C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\checkpoint-1060] due to args.save_total_limit
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model\tokenizer_config.json
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model\tokenizer_config.json

[M7] Running development prediction and final metrics

The following columns in the test set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Prediction *****
  Num examples = 30
  Batch size = 64

[M7] COMPLETE m1 / synthetic_pretrain / seed 2026 / attempt 002; dev CER=0.23472429210134127

[M7] START m1 / gold_finetune_continuous / seed 2026 / attempt 001 (trained)
[M7] Output: C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001
[M7] Loading C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model

loading configuration file C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model\config.json
loading configuration file C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model\config.json
You are using a model of type `wolof_tnt_hybrid_transformer` to instantiate a model of type ``. This may be expected if you are loading a checkpoint that shares a subset of the architecture (e.g., loading a `sam2_video` checkpoint into `Sam2Model`), but is otherwise not supported and can yield errors. Please verify that the checkpoint is compatible with the model you are instantiating.
Model config PreTrainedConfig {
  "architectures": [
    "TntHybridTransformerForConditionalGeneration"
  ],
  "attention_heads": 4,
  "bos_token_id": 1,
  "boundary_class_weights": [
    0.5533591001386836,
    1.2271996237756158,
    4.0,
    4.0
  ],
  "boundary_confidence_threshold": 0.6,
  "boundary_loss_weight": 0.5,
  "character_loss_weight": 1.0,
  "d_model": 192,
  "decoder_start_token_id": 1,
  "dropout": 0.1,
  "dtype": "float32",
  "encoder_layers": 3,
  "eos_token_id": 2,
  "feed_forward_size": 768,
  "hidden_size": 192,
  "is_encoder_decoder": true,
  "label_smoothing": 0.1,
  "max_position_embeddings": 256,
  "num_boundary_actions": 4,
  "num_operations": 4,
  "num_word_actions": 2,
  "operation_class_weights": [
    0.5553579980883788,
    1.9817851870151133,
    1.6380424851581792,
    2.76939125025622
  ],
  "operation_loss_weight": 1.0,
  "output_slots_per_source": 16,
  "pad_token_id": 0,
  "space_token_id": 4,
  "transformers_version": "5.5.4",
  "use_boundary_inference": true,
  "use_word_keep_gate": true,
  "vocab_size": 120,
  "word_class_weights": [
    0.9769410897842448,
    1.0247727727007534
  ],
  "word_keep_threshold": 0.8,
  "word_loss_weight": 0.5
}

loading configuration file C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model\config.json
Model config TntHybridConfig {
  "architectures": [
    "TntHybridTransformerForConditionalGeneration"
  ],
  "attention_heads": 4,
  "bos_token_id": 1,
  "boundary_class_weights": [
    0.5533591001386836,
    1.2271996237756158,
    4.0,
    4.0
  ],
  "boundary_confidence_threshold": 0.6,
  "boundary_loss_weight": 0.5,
  "character_loss_weight": 1.0,
  "d_model": 192,
  "decoder_start_token_id": 1,
  "dropout": 0.1,
  "dtype": "float32",
  "encoder_layers": 3,
  "eos_token_id": 2,
  "feed_forward_size": 768,
  "hidden_size": 192,
  "is_encoder_decoder": true,
  "label_smoothing": 0.1,
  "max_position_embeddings": 256,
  "model_type": "wolof_tnt_hybrid_transformer",
  "num_boundary_actions": 4,
  "num_operations": 4,
  "num_word_actions": 2,
  "operation_class_weights": [
    0.5553579980883788,
    1.9817851870151133,
    1.6380424851581792,
    2.76939125025622
  ],
  "operation_loss_weight": 1.0,
  "output_slots_per_source": 16,
  "pad_token_id": 0,
  "space_token_id": 4,
  "transformers_version": "5.5.4",
  "use_boundary_inference": true,
  "use_word_keep_gate": true,
  "vocab_size": 120,
  "word_class_weights": [
    0.9769410897842448,
    1.0247727727007534
  ],
  "word_keep_threshold": 0.8,
  "word_loss_weight": 0.5
}

loading weights file C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model\model.safetensors
Will use dtype=torch.float32 as defined in model's config object
Generate config GenerationConfig {
  "bos_token_id": 1,
  "decoder_start_token_id": 1,
  "eos_token_id": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "pad_token_id": 0
}

Loading weights:   0%|          | 0/46 [00:00<?, ?it/s]

loading configuration file C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\synthetic_pretrain\attempt_002\best_model\generation_config.json
Generate config GenerationConfig {
  "assistant_confidence_threshold": 0.4,
  "assistant_lookbehind": 10,
  "bos_token_id": 1,
  "decoder_start_token_id": 1,
  "diversity_penalty": 0.0,
  "do_sample": false,
  "early_stopping": false,
  "encoder_no_repeat_ngram_size": 0,
  "encoder_repetition_penalty": 1.0,
  "eos_token_id": [
    2
  ],
  "epsilon_cutoff": 0.0,
  "eta_cutoff": 0.0,
  "length_penalty": 1.0,
  "max_length": 20,
  "min_length": 0,
  "no_repeat_ngram_size": 0,
  "num_assistant_tokens": 20,
  "num_assistant_tokens_schedule": "constant",
  "num_beam_groups": 1,
  "num_beams": 1,
  "num_return_sequences": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_scores": false,
  "pad_token_id": 0,
  "remove_invalid_values": false,
  "repetition_penalty": 1.0,
  "return_dict_in_generate": false,
  "target_lookbehind": 10,
  "temperature": 1.0,
  "top_k": 50,
  "top_p": 1.0,
  "typical_p": 1.0,
  "use_cache": true
}

[M7] Loaded 1,779,274 total parameters; training 1,779,274 (100.0000%) via full_finetune
[M7] Tokenizing 142 training and 30 development pairs

Tokenizing TNT edit pairs:   0%|          | 0/142 [00:00<?, ? examples/s]

Tokenizing TNT edit pairs:   0%|          | 0/30 [00:00<?, ? examples/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
PyTorch: setting up devices

[M7] TNT evaluation route: parallel edit reconstruction; implementation=C:\Users\thioy\Desktop\School\PFE\src\modeling\tnt_hybrid_transformer.py; sha256=46ba78889f26
[M7] Training starts: 142 rows, 20 epochs, physical batch 32, accumulation 1
[M7] Checkpoints are selected by generated development CER every 5 epoch(s)

The following columns in the Training set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.
***** Running training *****
  Num examples = 142
  Num Epochs = 20
  Num update steps per epoch = 5
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 100
  Number of trainable parameters = 1,779,274

The following columns in the Evaluation set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-25\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-75
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-75\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-75\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-75\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-75\tokenizer_config.json
The following columns in the Evaluation set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 30
  Batch size = 64
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100\tokenizer_config.json


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-50 (score: 0.20044709388971685).
Deleting older checkpoint [C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\checkpoint-100] due to args.save_total_limit
Saving model checkpoint to C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model\config.json
Configuration saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model\generation_config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model\model.safetensors
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model\tokenizer_config.json
tokenizer config file saved in C:\Users\thioy\Desktop\School\PFE\checkpoints\m7_seq2seq\tnt_hybrid_m1_gate_v2\m1\seed_2026\gold_finetune_continuous\attempt_001\best_model\tokenizer_config.json

[M7] Running development prediction and final metrics

The following columns in the test set don't have a corresponding argument in `TntHybridTransformerForConditionalGeneration.forward` and have been ignored: source_id, target_text, source_text. If source_id, target_text, source_text are not expected by `TntHybridTransformerForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Prediction *****
  Num examples = 30
  Batch size = 64

[M7] COMPLETE m1 / gold_finetune_continuous / seed 2026 / attempt 001; dev CER=0.20044709388971685
[compact benchmark] m1: continuous 20-epoch gold run complete; selected dev CER=0.20044709388971685

{'rows': 30,
 'cer': 0.20044709388971685,
 'wer': 0.6610169491525424,
 'chrf': 56.46345131346913,
 'exact_match': 0.0,
 'correction_tp': 2,
 'correction_fp': 76,
 'correction_fn': 70,
 'correction_precision': 0.02564102564102564,
 'correction_recall': 0.027777777777777776,
 'correction_f1': 0.026666666666666665,
 'overcorrection_rate': 0.9743589743589743,
 'unchanged_reference_rows': 0,
 'unchanged_sentence_overcorrection_rate': 0.0}

## 4. Gate decision on raw Gold-dev references

The table recomputes the frozen TNT V1 M1 metrics against the original Gold-dev text, avoiding the former decoded-reference issue. The strict gate requires non-worse CER, improved WER and correction F1, reduced overcorrection, and at least one true correction.

In [6]:
summary = gate_summary(gold['dev'])
preferred = [
    'condition', 'cer', 'wer', 'chrf', 'exact_match',
    'correction_tp', 'correction_fp', 'correction_fn',
    'correction_precision', 'correction_recall', 'correction_f1',
    'overcorrection_rate',
]
display(summary[[column for column in preferred if column in summary.columns]])
display(gate_decision(summary))

,condition,cer,wer,chrf,exact_match,correction_tp,correction_fp,correction_fn,correction_precision,correction_recall,correction_f1,overcorrection_rate
0,identity,0.233234,0.630508,56.052143,0.0,0,0,72,0.000000,0.000000,0.000000,0.000000
1,tnt_v1_m1,0.181073,0.667797,55.888125,0.0,2,67,70,0.028986,0.027778,0.028369,0.971014
2,tnt_hybrid_m1,0.200447,0.661017,56.463451,0.0,2,76,70,0.025641,0.027778,0.026667,0.974359

{'ready': True,
 'proceed_to_ablation': False,
 'criteria': {'cer_not_worse_than_v1': False,
  'wer_improved_over_v1': True,
  'correction_f1_improved': False,
  'overcorrection_reduced': False,
  'at_least_one_true_correction': True},
 'note': 'A failed strict gate triggers head diagnostics, not Gold-test evaluation or automatic full-benchmark training.'}

## 5. Qualitative comparison

Inspect whether metric changes correspond to correct normalization rather than more edits or identity copying.

In [7]:
comparison = gate_prediction_comparison(gold['dev'])
display(comparison)

,source_id,source_text,reference,prediction_tnt_v1_m1,prediction_tnt_hybrid_m1
0,gold:dev:10000,​ té dou wakhé dank,té du waxee ndànk,te du waxe dank,te du waxe daank
1,gold:dev:10003,cachet wam mo wara diekh. sokhna ak salimata l...,cachet wam moo wara jeex sokhna ak salimata lé...,cachet wam mo wara djeex. soxna ak salimata le...,cachet wam moo waara jeex. soxna ak salimata l...
2,gold:dev:10005,nimako diépé sakh da eupeu,ni ma ko jéppe sax da ëpp,nimako diépé sax da ëpë,nimako diépe sax da ëpë
3,gold:dev:10007,maman oumy mome rk lay bagna guis,maman oumy moom rek laay baña gis,maman oumy mome rk lay bañña gis,maman oumy moom rk lay baaa ggis
4,gold:dev:10008,mére bi mo sof ba paré reuy lamign,mère bi moo soof ba pare réy làmmiñ,mére bi mo sof ba pare rëy lamigñ,mére bi moo soof ba pare rëy lamie
5,gold:dev:10013,franchement khady thiam nak dafa eupeul fi kou...,franchement khady thiam nak dafa ëppal fi kuy ...,franchement hady ciam nak dafa ëpël fi kuy sëy...,franceement xady cam nak dafa ëpël fi kuy sëy ...
6,gold:dev:10014,loutakh pere ndiouga di raamal vieux?alors que...,lu tax pere ndiouga di raamal vieux alors que ...,lutax per ndjouga di raamal viëëx?alors qu ñoo...,utax pere njñuga i raamal vjëx?aloors q ñoo bo...
7,gold:dev:10020,ki di way baabel voix bi nèx na deh kanla,ki di woy baabel voix bi neex na de kan la,ki di way baabel voix bi nèx na dnx kanla,ki di waay baabel voix bi nèx na dne kanla
8,gold:dev:10021,maman omou kiye rayé si série douko ray,maman omou kuy reye ci série du ko rey,maman omou kiy raye si sérin duko ray,maman omu kiyé raye si serjc duko ray
9,gold:dev:10026,le meilleurs séries kou d'accord lalal j'aime ️,les meilleurs séries ku d'accord laalal j'aime,le meilleërs séries ku d'accord lalal j'aim ️,le meillërs seeries ku d'accord lalal j'aimé ️
10,gold:dev:10031,dafay beug rew soff la deff,dafay bëgg reew soof lay def,dafay begg rew soff la deff,dafay bëgg rew sooff la deff
11,gold:dev:10032,bako ba tidiane nop boy bou khess bi,ba ko ba tidiane nob boy bu xees bi,bako ba tidjann nop boy bu eess bi,bako ba tijjann nop booy bu xxess bi
12,gold:dev:10034,wakh nako facebook néna kouy seuy rék meusseu ...,wax naa ko facebook ne naa kuy séy rek mës nga...,wakh nako facbook nena kuy sëy rek mëssë ngëa ...,wax nakoo facebóok nena kuy sëy rek mëssë nga ...
13,gold:dev:10036,djickom bu besss bii sakh diapout koo,jikkom bu bees bii sax jàppu ko,jickom bu besss bii sax jaàpout koo,jickom bu beesss bii sax aàput kóoo
14,gold:dev:10037,moma diaxal deh mane miii,mooma jaaxal de man mii,moma jaxal dex mann mji,moma jaxal dee mann miii
15,gold:dev:10038,khana yaya dou mere,xanaa yaya du mer,khana yaya du mere,hana yaya du mere
16,gold:dev:10040,bly ndax niou nopalou,bilay ndax ñu noppalu,bly ndax njñu nopalu,bly ndax noñu nopalu
17,gold:dev:10042,​ mayko lolou,may ko loolu,mayko lolu,N mayko loou
18,gold:dev:10043,kou masoul sétane publicité comme mane rk lale...,ku masul seetaan publicité comme man rek lale ...,ku masoul sétan publicite comm mann rk lal j'aime,u maasul seetaan p blicite comm mann rk lalé j...
19,gold:dev:10044,kou beugeu papa diouga take niarel lalal j'aime,ku bëgg papa diouga takk ñaarel laalal j'aime,ku bëgë papa djuuga take naarel lalal j'aime,u bëëgë papa jñgga taë aarel lalal j'aim
20,gold:dev:10045,ibnou thiam ma diwal la sa mourou bi café wala,ibnou caam ma diwal la sa mburu bi café wala,ibnou thiam ma diwal la sa muru bi cafe wala,jbnou thiam ma iwaal la sa muru bi cafe wala
21,gold:dev:10048,mere bi nenako inou ma diwal la sa mbourou bi ...,mere bi ne na ko inou ma diwal la sa mburu bi ...,mere bi nenako inñu ma jiwal la sa mburu bi cafe,mere bi nenakoo inu ma diwal la sa mburu bi cafe
22,gold:dev:10049,l'i mo nekhe way,lii moo neex waay,l'i mo neeee way,l'i moo neexx waay
23,gold:dev:10050,khady thiam diépinako,khady thiam jéppi na ko,khady thiam jepinako,khady thiam deépinakoo
24,gold:dev:10051,wa khana nekoul salimata mo aye thiéré bi,waa xanaa nekkul salimata moo ay cere bi,wa khana nekul salimata mo ay hcere bi,Waa kxana nekul salimata moo ayé ccere bi
25,gold:dev:10052,"wa khalil mi wérna, mounane ay deuk ak dialika...",waa khalil mi wér na mu naan ay dëkk ak dialik...,"wa khalil mi wérna, munann ay dëëk ak jjalika,...","Waa kxalil mi weerna, munan ay dëk ak aalika, ..."
26,gold:dev:10055,ana niou dieupyy mame oumy comme mane topou là...,ana ñu jéppi mame oumy comme man topp la mais ...,ana njóu djëpyy mame umy comme mann topu là ma...,ana noou jëpyy mam umy coomme man topu là mais...
27,gold:dev:10060,naniou ko may yayou amina si lady diama femme ...,na ñu ko may yaayu amina ci lady diama femme b...,naniou ko may yayu amina si lady djàma femm bo...,naniu ko maay yayuu amina si laady aàma femme ...
28,gold:dev:10061,dafka waronna wakh waw bakham foumoukoy diw,daf ka waroona wax waw ba xam fu mu koy diw,dafka waronna wakx waw baxam fumukoy jiw,dafka waron a wax waw baxam fumukooy diw
29,gold:dev:10062,moma diakhal nakk,mooma jaaxal nak,moma jakxal nakk,moma jaxal nakk

## 6. Diagnose the trained heads

This is read-only inference on Gold-dev. It exports raw and effective character-operation predictions, boundary decisions, word KEEP/EDIT probabilities, confusion matrices, and lookup-based French/entity/protection subsets. It does not retrain or evaluate Gold-test.

In [ ]:
head_summary = run_head_diagnostics(gold['dev'])
print('Saved under:', DIAGNOSTIC_DIR.resolve())
display(pd.DataFrame(head_summary['operation']['raw_per_class']))
display(pd.DataFrame(head_summary['operation']['effective_per_class']))
display(pd.DataFrame(head_summary['boundary']['per_class']))
display(pd.DataFrame(head_summary['word']['per_class']))
display({
    'operation_confidence': head_summary['operation']['confidence'],
    'segment': head_summary['segment'],
    'boundary_actions': head_summary['boundary']['accepted_actions'],
    'word_keep_gate_rate': head_summary['word']['keep_gate_rate'],
    'gold_edit_incorrectly_blocked': head_summary['word']['gold_edit_incorrectly_blocked'],
    'known_french': head_summary['word']['known_french'],
    'known_entities': head_summary['word']['known_entities'],
    'known_protected': head_summary['word']['known_protected'],
})

In [ ]:
word_diagnostics = pd.read_csv(DIAGNOSTIC_DIR / 'word_predictions.csv', keep_default_na=False)
print('Gold KEEP words not protected by the confidence gate:')
display(
    word_diagnostics.loc[
        word_diagnostics['gold_word_action'].eq('keep')
        & ~word_diagnostics['keep_gate_applied']
        [
            'source_id', 'source_word', 'keep_probability',
            'raw_character_edit_positions', 'lookup_language',
            'lookup_entity_type', 'lookup_protected',
        ],
    ].sort_values(['raw_character_edit_positions', 'keep_probability'], ascending=[False, True]).head(30)
)

print('Gold EDIT words incorrectly blocked by the KEEP gate:')
display(
    word_diagnostics.loc[
        word_diagnostics['gold_word_action'].eq('edit')
        & word_diagnostics['keep_gate_applied']
    ].sort_values('keep_probability', ascending=False).head(30)
)